# (APPENDIX) Apendices {-} 

```{r , child = '_global_options.Rmd'}
```

# Enlaces {#links}


**Recursos para el aprendizaje de R** (  <https://rubenfcasal.github.io/post/ayuda-y-recursos-para-el-aprendizaje-de-r>
): A continuación se muestran algunos recursos que pueden ser útiles para el aprendizaje de R y la obtención de ayuda...


***Ayuda online***:

- Ayuda en línea sobre funciones o paquetes: [RDocumentation](https://www.rdocumentation.org/)

- Buscador [RSeek](http://rseek.org/)

- [StackOverflow](http://stackoverflow.com/questions/tagged/r)


***Cursos***:
algunos cursos gratuitos:
   
- [Coursera](https://www.coursera.org/):

    - [Introducción a Data Science: Programación Estadística con  R](https://www.coursera.org/learn/intro-data-science-programacion-estadistica-r)

    - [Mastering Software Development in R](https://www.coursera.org/specializations/r)

<!-- -->

- [DataCamp](https://www.datacamp.com/courses):

    - [Introducción a R](https://www.datacamp.com/courses/introduccion-a-r/)
  
<!-- -->
  
- [Stanford online](http://online.stanford.edu/courses):

    - [Statistical Learning](http://online.stanford.edu/course/statistical-learning)
  
<!-- -->

- Curso UCA: [Introducción a R, R-commander y shiny](http://knuth.uca.es/moodle/course/view.php?id=51)

<!-- -->

- Udacity: [Data Analysis with R](https://eu.udacity.com/course/data-analysis-with-r--ud651)

<!-- -->

- [Swirl Courses](https://swirlstats.com/scn/title.html):
  se pueden hacer cursos desde el propio R con el paquete
  [swirl](https://swirlstats.com).

<!-- 
Preparar curso con el paquete swirl?
-->

Para información sobre cursos en castellano se puede recurrir a la web de [R-Hispano](http://r-es.org/) en el apartado [formación](http://r-es.org/category/formacion). Algunos de los cursos que aparecen en entradas antiguas son gratuitos. 
Ver: [Cursos MOOC relacionados con R](http://r-es.org/2016/02/12/cursos-masivos-y-otra-formacion-on-line-sobre-r/).


***Libros***

* ***Iniciación***:
    
    - 2011 - The Art of R Programming. A Tour of Statistical Software Design, 
      ([No Starch Press](https://www.nostarch.com/artofr.htm))
    
    - R for Data Science
      ([online](http://r4ds.had.co.nz/), [O'Reilly](http://shop.oreilly.com/product/0636920034407.do))
    
    - Hands-On Programming with R: Write Your Own Functions and Simulations, 
      by Garrett Grolemund 
      ([O'Reilly](http://shop.oreilly.com/product/0636920028574.do))
    
* ***Avanzados***:
    
    - 2008 - Software for Data Analysis: Programming with R - Chambers
      ([Springer](http://www.springer.com/la/book/9780387759357))
    
    - Advanced R by Hadley Wickham
      (online: [1ª ed](http://adv-r.had.co.nz/), 
      [2ª ed](https://adv-r.hadley.nz/), 
      [Chapman & Hall](https://www.amazon.com/dp/1466586966))
    
    - R packages by Hadley Wickham
      ([online](http://r-pkgs.had.co.nz/),
      [O'Reilly](http://shop.oreilly.com/product/0636920034421.do))

* ***Bookdown***:
  el paquete [`bookdown`](https://bookdown.org) de R permite escribir libros empleando 
  [R Markdown](http://rmarkdown.rstudio.com) y compartirlos. 
  En https://bookdown.org está disponible una selección de libros escritos con este paquete 
  (un listado más completo está disponible [aquí](https://bookdown.org/home/archive/)).
  Algunos libros en este formato en castellano son:
    
    - [Prácticas de Simulación](https://rubenfcasal.github.io/simbook)
      (disponible en el repositorio de GitHub
      [rubenfcasal/simbook](https://github.com/rubenfcasal/simbook)).
      
    - [Escritura de libros con bookdown](https://rubenfcasal.github.io/bookdown_intro/)
      (disponible en el repositorio de GitHub
      [rubenfcasal/bookdown_intro](https://github.com/rubenfcasal/bookdown_intro)).
    
    - [R para profesionales de los datos: una introducción](https://www.datanalytics.com/libro_r/index.html).
    
    - [Estadística Básica Edulcorada](https://bookdown.org/aquintela/EBE).


***Material online***:
en la web se puede encontrar mucho material adicional, por ejemplo:

- [CRAN: Other R documentation](https://www.r-project.org/other-docs.html)

- [RStudio](https://www.rstudio.com): 
  [Online learning](https://www.rstudio.com/online-learning), 
  [Webinars](https://resources.rstudio.com/webinars),
  [shiny](http://shiny.rstudio.com),
  [tidyverse](https://www.tidyverse.org/).
  
    - [CheatSheets](https://resources.rstudio.com/rstudio-cheatsheets):
      [RMarkdown](https://resources.rstudio.com/rstudio-cheatsheets/rmarkdown-2-0-cheat-sheet),
      [Shiny](https://resources.rstudio.com/rstudio-cheatsheets/shiny-cheat-sheet),
      [dplyr](https://github.com/rstudio/cheatsheets/blob/master/data-transformation.pdf),
      [tidyr](https://github.com/rstudio/cheatsheets/blob/master/data-import.pdf),
      [stringr](https://resources.rstudio.com/rstudio-cheatsheets/stringr-cheat-sheet).
      
      
- Blogs en inglés:

    - https://www.r-bloggers.com/

    - https://www.littlemissdata.com/blog/rstudioconf2019 
    
    - RStudio: https://blog.rstudio.com
    
    - Microsoft Revolutions: https://blog.revolutionanalytics.com


- Blogs en castellano:

    -  https://www.datanalytics.com
    
    -  http://oscarperpinan.github.io/R
  
    -  http://rubenfcasal.github.io
   
   
- Listas de correo:

    - Listas de distribución de r-project.org: https://stat.ethz.ch/mailman/listinfo
    
    - Búsqueda en R-help:  http://r.789695.n4.nabble.com/R-help-f789696.html
    
    - Búsqueda en R-help-es: https://r-help-es.r-project.narkive.com
      
        https://grokbase.com/g/r/r-help-es

    - Archivos de R-help-es: https://stat.ethz.ch/pipermail/r-help-es


## Forecasting: Principles and Practice {#forecast-links}

[Forecasting: Principles and Practice, 2ª ed](https://otexts.com/fpp2)
by Rob J. Hyndman and George Athanasopoulos:

* [3.1 Some simple forecasting methods](https://otexts.com/fpp2/simple-methods.html)

* [3.6 The forecast package in R](https://otexts.com/fpp2/the-forecast-package-in-r.html)

* [11.4 Bootstrapping and bagging](https://otexts.com/fpp2/bootstrap.html)

* [Appendix: For instructors](https://otexts.com/fpp2/appendix-for-instructors.html)


## Spatial data  {#spatial-links} 

*  [Apuntes de simulación ](https://rubenfcasal.github.io/simbook):

    - [9 Simulación de Distribuciones Multidimensionales ](https://rubenfcasal.github.io/simbook/simulacion-de-distribuciones-multidimensionales.html)
    
    - [9.3 Simulación condicional e incondicional ](https://rubenfcasal.github.io/simbook/simulacion-de-distribuciones-multidimensionales.html#simulacion-condicional-e-incondicional)

*  Castillo-Páez, S., Fernández-Casal, R., García-Soidán, P.
  [A nonparametric bootstrap method for spatial data ](https://www.sciencedirect.com/science/article/pii/S0167947319300325?via%3Dihub),
  Computational Statistics and Data Analysis, 137 (2019) 1-15. 

*  [Poster bootstrap condicional (pdf)](./Poster_METMA9_2.pdf)

*  [npsp](https://rubenfcasal.github.io/npsp/index.html), [post en castellano ](https://rubenfcasal.github.io/post/geoestadistica-no-parametrica-con-el-paquete-npsp/).

*  [Tesis geoestadística espacio-temporal (pdf) ](https://rubenfcasal.github.io/Geoestadistica_espacio-temporal.pdf)
